name: CI (indexing-worker)

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-indexing-worker.yaml"
      - "worker/**"
      - "shared/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-indexing-worker.yaml"
      - "worker/**"
      - "shared/**"

env:
  REGISTRY: rg.fr-par.scw.cloud/knot-dots

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - uses: docker/setup-buildx-action@v4
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: ./worker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.REGISTRY }}/indexing-worker:${{ github.sha }}
            ${{ env.REGISTRY }}/indexing-worker:latest
