name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v4
        with:
          file: docker/app/Dockerfile
          push: false
          tags: knot-dots/strategytool:${{ github.sha }}
