name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "terraform/**" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "terraform/**" ]

env:
  REGISTRY: rg.fr-par.scw.cloud/knot-dots

jobs:

  test:

    timeout-minutes: 60

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.32.0-focal

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx playwright test

  build:

    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/strategytool:latest
          cache-to: type=inline
          file: docker/app/Dockerfile
          target: production
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.REGISTRY }}/strategytool:${{ github.sha }}
            ${{ env.REGISTRY }}/strategytool:latest

  update:

#    if: github.event_name == 'push'

    needs: [ build ]

    runs-on: ubuntu-latest

    env:
      CI_COMMIT_MESSAGE: "Update image"
      CI_USER_EMAIL: "actions@github.com"
      CI_USER_NAME: "GitHub Actions"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          echo 'strategytool_image = "${{ env.REGISTRY }}/strategytool:${{ github.sha }}"' > ./terraform/dev/terraform.tfvars
          git config --global user.name "${{ env.CI_USER_NAME }}"
          git config --global user.email "${{ env.CI_USER_EMAIL }}"
          git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
          git push
