name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud/knot-dots
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=rg.fr-par.scw.cloud/knot-dots/strategytool:latest
          cache-to: type=inline
          file: docker/app/Dockerfile
          push: true
          tags: |
            rg.fr-par.scw.cloud/knot-dots/strategytool:${{ github.sha }}
            rg.fr-par.scw.cloud/knot-dots/strategytool:latest
