name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: rg.fr-par.scw.cloud/knot-dots

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/strategytool:latest
          cache-to: type=inline
          file: docker/app/Dockerfile
          target: production
          push: true
          tags: |
            ${{ env.REGISTRY }}/strategytool:${{ github.sha }}
            ${{ env.REGISTRY }}/strategytool:latest
