name: Mirroring

on: [push, delete]

jobs:
  to_opencode:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare "https://github.com/$GITHUB_REPOSITORY" .
      - run: git push --mirror "https://oauth2:${{ secrets.OPENCODE_PROJECT_TOKEN }}@gitlab.opencode.de/stadt-detmold/strategytool.git"
