name: Publisher

on:
  workflow_dispatch

env:
  REGISTRY: rg.fr-par.scw.cloud/knot-dots

jobs:

  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: [ "strategytool", "keycloak", "migrate" ]

    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ matrix.image }}:latest
          cache-to: type=inline
          file: docker/${{ matrix.image }}/Dockerfile
          target: production
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.image }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ matrix.image }}:latest


